export const RECEIVE_FILTERS = 'RECEIVE_FILTERS';
export const SET_CURRENT_QUERY = 'SET_CURRENT_QUERY';

export const ASYNC_ROUTINE_DISPATCH = 'ASYNC_ROUTINE_DISPATCH';

export const RESPONSES_FETCH = 'RESPONSES_FETCH';
export const RESPONSES_FETCH_RECEIVE = 'RESPONSES_FETCH_RECEIVE';
export const RESPONSES_FETCH_FAIL = 'RESPONSES_FETCH_FAIL';

export const RESPONSES_SELECTION_SET = 'RESPONSES_SELECTION_SET';

export const RESPONSES_LOADING_SET = 'RESPONSES_LOADING_SET';
